### ISSUE TITLE
UI: asked to log in 

### ISSUE THREAD

**Issue by LydiaKoerber** [satzbeleg/evidence-app#288]
home menu: always prompted to login even though user is logged in (confusing)
![WhatsApp Image 2023-06-08 at 16 47 03(1)](https://github.com/satzbeleg/evidence-app/assets/76654686/599faea9-ceb5-4fdd-b803-c9df7b042415)

**Comment by ulf1** [comment]
https://github.com/satzbeleg/evidence-app/commit/339486a7ff40b00c88c38df8c9ef5e732dba345b
